name: dms_stan
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::arviz
  - conda-forge::cmdstanpy
  - conda-forge::typeguard
  - conda-forge::hvplot
  - jupyter
  - panel
  - python=3.12
  - watchfiles