name: dms_stan
channels:
  - conda-forge
dependencies:
  - bokeh::jupyter_bokeh
  - conda-forge::arviz>=0.21
  - conda-forge::cmdstan
  - conda-forge::cmdstanpy
  - conda-forge::hvplot
  - conda-forge::seaborn
  - conda-forge::typeguard
  - dask
  - jupyter
  - pytorch::pytorch-cuda=12.4
  - panel
  - pip
  - pocl
  - python=3.12
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pyviz::datashader
  - watchfiles
  - pip:
    - -e .