name: scistanpy
channels:
  - conda-forge
dependencies:
  - bokeh::jupyter_bokeh
  - conda-forge::arviz>=0.21
  - conda-forge::biopython
  - conda-forge::cmdstan
  - conda-forge::cmdstanpy
  - conda-forge::hvplot
  - conda-forge::seaborn
  - conda-forge::typeguard
  - dask
  - jupyter
  - panel
  - pip
  - pocl
  - python=3.12
  - pyviz::datashader
  - sphinx
  - watchfiles
  - pip:
    - torch --index-url https://download.pytorch.org/whl/cu128
    - torchvision --index-url https://download.pytorch.org/whl/cu128
    - torchaudio --index-url https://download.pytorch.org/whl/cu128
    - twine
    - keyring
    - artifacts-keyring
    - -e .