name: dms_stan
channels:
  - defaults
  - conda-forge
dependencies:
  - bokeh::jupyter_bokeh
  - conda-forge::arviz
  - conda-forge::cmdstanpy
  - conda-forge::hvplot
  - conda-forge::typeguard
  - dask
  - jupyter
  - pytorch::pytorch-cuda=12.4
  - panel
  - pip
  - python=3.12
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pyviz::datashader
  - watchfiles